import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

const MAPPING = {
  "house.fill": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "magnifyingglass": "search",
  "cart.fill": "shopping-cart",
  "bag.fill": "shopping-bag",
  "person.fill": "person",
  "list.bullet": "receipt-long",
  "heart.fill": "favorite",
  "heart": "favorite-border",
  "star.fill": "star",
  "star": "star-border",
  "location.fill": "location-on",
  "clock.fill": "schedule",
  "shippingbox.fill": "local-shipping",
  "bolt.fill": "bolt",
  "gift.fill": "card-giftcard",
  "creditcard.fill": "credit-card",
  "checkmark.circle.fill": "check-circle",
  "xmark.circle.fill": "cancel",
  "arrow.left": "arrow-back",
  "plus": "add",
  "minus": "remove",
  "trash.fill": "delete",
  "ellipsis": "more-horiz",
  "info.circle.fill": "info",
  "bell.fill": "notifications",
  "gearshape.fill": "settings",
  "questionmark.circle.fill": "help",
  "arrow.right": "arrow-forward",
  "mappin.and.ellipse": "place",
  "phone.fill": "phone",
  "envelope.fill": "email",
  "lock.fill": "lock",
  "person.badge.shield.checkmark.fill": "verified-user",
  "doc.text.fill": "description",
  "square.and.arrow.up.fill": "share",
  "storefront.fill": "storefront",
  "building.2.fill": "business",
  "clock.arrow.circlepath": "history",
  "chart.bar.fill": "bar-chart",
  "dollarsign.circle.fill": "attach-money",
  "tray.full.fill": "inventory",
  "checkmark.seal.fill": "verified",
  "exclamationmark.triangle.fill": "warning",
  "arrow.triangle.2.circlepath": "sync",
  "person.2.fill": "people",
  "hand.thumbsup.fill": "thumb-up",
  "hand.thumbsdown.fill": "thumb-down",
  "photo.fill": "photo",
  "pencil": "edit",
  "calendar": "event",
  "banknote.fill": "account-balance-wallet",
  "circle": "radio-button-unchecked",
  "car.fill": "directions-car",
  "figure.walk": "directions-walk",
  "bicycle": "pedal-bike",
  "power": "power-settings-new",
  "map.fill": "map",
  "location.north.line.fill": "navigation",
  "scope": "my-location",
  "timer": "timer",
  "flag.fill": "flag",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "stop.fill": "stop",
  "arrow.up.circle.fill": "arrow-upward",
  "dollarsign.arrow.circlepath": "currency-exchange",
  "wallet.pass.fill": "account-balance-wallet",
  "speedometer": "speed",
  "shield.fill": "shield",
  "doc.badge.plus": "note-add",
  "camera.fill": "camera-alt",
  "hand.raised.fill": "pan-tool",
  "bubble.left.fill": "chat-bubble",
  "trophy.fill": "emoji-events",
  "shield.lefthalf.filled": "admin-panel-settings",
  "rectangle.grid.2x2.fill": "dashboard",
  "person.crop.circle.badge.checkmark": "how-to-reg",
  "exclamationmark.circle.fill": "error",
  "arrow.clockwise": "refresh",
  "slider.horizontal.3": "tune",
  "percent": "percent",
  "megaphone.fill": "campaign",
  "wrench.fill": "build",
  "eye.fill": "visibility",
  "nosign": "block",
} as unknown as IconMapping;

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
